name: Custom / CI

on:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: ipc-sim/ipc-toolkit
      - name: Checkout cibuildwheel config
        uses: actions/checkout@v6
        with:
          path: tmp.wbc9ar41ex
          sparse-checkout: pyproject.toml
      - name: Install Ccache
        run: sudo apt-get --yes install ccache
      - id: ccache
        name: Get ccache config
        run: echo "cache_dir=$(ccache --get-config 'cache_dir')" >> "$GITHUB_OUTPUT"
      - name: Ccache
        uses: actions/cache@v5
        with:
          path: ${{ steps.ccache.outputs.cache_dir }}
          key: ccache-${{ runner.os }}-${{ runner.arch }}
      - name: Ccache zero stats
        run: ccache --zero-stats
      - name: cibuildwheel
        uses: pypa/cibuildwheel@v3.4
        with:
          config-file: tmp.wbc9ar41ex/pyproject.toml
        env:
          CCACHE_DIR: /host/${{ steps.ccache.outputs.cache_dir }}
      - name: Ccache stats
        run: ccache --show-stats
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: wheelhouse
          path: wheelhouse/*.whl

  release:
    name: Release
    permissions:
      actions: write
      contents: write
    needs:
      - build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          name: wheelhouse
          path: wheelhouse
      - name: Delete stale release
        run: gh release delete 'latest' --cleanup-tag --yes --repo '${{ github.repository }}'
        env:
          GH_TOKEN: ${{ github.token }}
        continue-on-error: true
      - name: Create GitHub release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: latest
          files: wheelhouse/*.whl
      - name: Build Index
        run: gh workflow run 'custom-index.yaml' --repo '${{ github.repository }}'
        env:
          GH_TOKEN: ${{ github.token }}

  index:
    name: Index
    permissions:
      id-token: write
      pages: write
    needs:
      - release
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v6
      - name: Install mise
        uses: jdx/mise-action@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v8.1.0
      - name: Build Index
        run: mise run gen:index
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: gh-pages
      - id: deploy
        name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v5
